### ISSUE TITLE
Mycorrhiza problem

### ISSUE THREAD

**Issue by rhaphael** [jgeofil/mycorrhiza#6]
I tried to run Mycorrhiza examples with Ubuntu 18.04.4 using the python script, but the following error occurs:

Outputting data in Nexus format.: 100%|████████| 90/90 [00:00<00:00, 939.25it/s]
Building network from file data/JN3L2X7MA3CPN57GYCSHLV21EUVZNONP.nex
SplitsTree -g -v -i /home/rhaphael/Desktop/Mycorrhiza/mycorrhiza-master/examples/data/JN3L2X7MA3CPN57GYCSHLV21EUVZNONP.nex
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rhaphael/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/rhaphael/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/analysis/analysis.py", line 141, in func
    return sn.execute_nexus_file(file)
  File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/network/network.py", line 25, in execute_nexus_file
    bash_nexus_file(filename)
  File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/network/network.py", line 40, in bash_nexus_file
    process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE, shell=True if os_name == 'Windows' else False)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'SplitsTree': 'SplitsTree'
"""
How do I solve this problem (error)?

**Comment by rhaphael** [comment]
> I tried to run Mycorrhiza examples with Ubuntu 18.04.4 using the python script, but the following error occurs:
> 
> Outputting data in Nexus format.: 100%|████████| 90/90 [00:00<00:00, 939.25it/s]
> Building network from file data/JN3L2X7MA3CPN57GYCSHLV21EUVZNONP.nex
> SplitsTree -g -v -i /home/rhaphael/Desktop/Mycorrhiza/mycorrhiza-master/examples/data/JN3L2X7MA3CPN57GYCSHLV21EUVZNONP.nex
> multiprocess.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/home/rhaphael/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 119, in worker
> result = (True, func(*args, **kwds))
> File "/home/rhaphael/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 44, in mapstar
> return list(map(*args))
> File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/analysis/analysis.py", line 141, in func
> return sn.execute_nexus_file(file)
> File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/network/network.py", line 25, in execute_nexus_file
> bash_nexus_file(filename)
> File "/home/rhaphael/.local/lib/python3.6/site-packages/mycorrhiza/network/network.py", line 40, in bash_nexus_file
> process = subprocess.Popen(bash_command.split(), stdout=subprocess.PIPE, shell=True if os_name == 'Windows' else False)
> File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> restore_signals, start_new_session)
> File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'SplitsTree': 'SplitsTree'
> """
> How do I solve this problem (error)?

**Comment by RGoess** [comment]
Have you installed Splitstree in your home directory? (http://www.splitstree.org/)

**Comment by mizubuti** [comment]
Yes, I had it installed on my home directory.
